### ISSUE TITLE
Support multiple services / fanout ingress routing

### ISSUE THREAD

**Issue by boundless-thread** [GoogleCloudPlatform/k8s-multicluster-ingress#202]
I don't think this is currently possible with kubemci.  I've searched and came up with nothing.  It would be nice if kubemci could support multiple services ( Example at step 6: https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer) and URL path routing for HTTP requests to those services.

**Comment by nikhiljindal** [comment]
Thanks for filling the issue!

I havent tried it out myself, but I expect it to work. Can you send more details?
Does kubemci throw an error or create runs successfully but doesnt do whats expected?

**Comment by boundless-thread** [comment]
My `mciingress.yml`: 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: api-mci-ip
    kubernetes.io/ingress.class: gce-multi-cluster
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: api-1
          servicePort: 8080
      - path: /v2/*
        backend:
          serviceName: api-2
          servicePort: 8080
```

Running 
```
$ kubemci create api --ingress=./mcingress.yml --gcp-project=XXX --kubeconfig=./mcikubeconfig
```

Returns
```
Error: Error in creating load balancer: 1 error occurred:

* unexpected: ing.spec.backend is nil. Multicluster ingress needs a user-specified default backend
```

**Comment by boundless-thread** [comment]
Ah ok.  I think i see how to achieve this now. Thank you.

**Comment by lfallet** [comment]
For people encountering this error, here is the ingress with default backend from above example:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: api-mci-ip
    kubernetes.io/ingress.class: gce-multi-cluster
spec:
  backend:
    serviceName: api-1
    servicePort: 8080
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: api-1
          servicePort: 8080
      - path: /v2/*
        backend:
          serviceName: api-2
          servicePort: 8080
```

Adding this default backend allows mci to be successfully created with additional *path* or *host* rules.
