### ISSUE TITLE
Support for backend buckets

### ISSUE THREAD

**Issue by process0** [GoogleCloudPlatform/k8s-multicluster-ingress#214]
Is there a way to define a route to a backend bucket on GCP using the MCI yaml file?  I know I can edit the Load Balancer to add the route manually using the GCP web UI.  I can also manually edit the URL maps file using gcloud and a file editor, but there is no nice way to automate this.  

I suggest having `bucketName` and `bucketCdn` elements for the `backend` section.  We could check for the existence of the cloud storage bucket, and create the backend bucket if it exists or fail if it does not exist.

```
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 8080
  rules:
  - http:
      paths:
      - path: "/api/*"
        backend:
          serviceName: "api"
          servicePort: 3000
      - path: "/static/*"
        backend:
          bucketName: "api-assets"
          bucketCdn: true
```

**Comment by cagataygurturk** [comment]
Hello @nikhiljindal , I am planning to add storage bucket storage to kubemci. The design in my mind is like following:

- Every cluster would have a headless service with an annotation pointing out to storage bucket

```
apiVersion: v1
kind: Service
metadata:
  name: prod-static-bucket
  labels:
    app: djangoapp
  annotations:
    kubernetes.io/ingress.storage-bucket-name: "bucket_name"
spec:
  clusterIP: None
```

Then this service would be referred in standard Ingress resource:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zoneprinter
  annotations:
    kubernetes.io/ingress.class: gce-multi-cluster
    kubernetes.io/ingress.global-static-ip-name: $ZP_KUBEMCI_IP
spec:
  rules:
  - http:
      paths:
      - path: "/static/*"
        backend:
          serviceName: "api"
          servicePort: 3000
```

In addition, [BackendConfig](https://cloud.google.com/kubernetes-engine/docs/how-to/cdn-backendconfig) can be supported by kubemci to enable CDN for this endpoints.

What do you think?
